// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: booking.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :exec
INSERT INTO bookings (
        booking_id,
        user_id,
        event_id,
        seat_number,
        booking_status,
        created_at
    )
VALUES (
        $1::uuid,
        $2::uuid,
        $3::uuid,
        $4::varchar,
        $5::varchar,
        $6::timestamptz
    )
`

type CreateBookingParams struct {
	BookingID     uuid.UUID          `json:"booking_id"`
	UserID        uuid.UUID          `json:"user_id"`
	EventID       uuid.UUID          `json:"event_id"`
	SeatNumber    string             `json:"seat_number"`
	BookingStatus string             `json:"booking_status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// Step 3 in the sequence diagram (design doc Section 4.1): persist a PENDING
// record before attempting the Redis lock, so even a failed lock attempt
// leaves an auditable row.
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) error {
	_, err := q.db.Exec(ctx, createBooking,
		arg.BookingID,
		arg.UserID,
		arg.EventID,
		arg.SeatNumber,
		arg.BookingStatus,
		arg.CreatedAt,
	)
	return err
}

const findExpiredLocks = `-- name: FindExpiredLocks :many
SELECT booking_id,
    user_id,
    event_id,
    seat_number,
    booking_status,
    locked_until,
    created_at,
    confirmed_at,
    cancelled_at
FROM bookings
WHERE booking_status = 'LOCKED'
    AND locked_until < $1::timestamptz
`

// Input to the background TTL watcher (design doc Section 3.3.1, "automatic
// reconciliation") — bookings stuck in LOCKED whose TTL has already passed.
func (q *Queries) FindExpiredLocks(ctx context.Context, asOf pgtype.Timestamptz) ([]Booking, error) {
	rows, err := q.db.Query(ctx, findExpiredLocks, asOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.BookingID,
			&i.UserID,
			&i.EventID,
			&i.SeatNumber,
			&i.BookingStatus,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT booking_id,
    user_id,
    event_id,
    seat_number,
    booking_status,
    locked_until,
    created_at,
    confirmed_at,
    cancelled_at
FROM bookings
WHERE booking_id = $1::uuid
`

func (q *Queries) GetBookingByID(ctx context.Context, bookingID uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, bookingID)
	var i Booking
	err := row.Scan(
		&i.BookingID,
		&i.UserID,
		&i.EventID,
		&i.SeatNumber,
		&i.BookingStatus,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.CancelledAt,
	)
	return i, err
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT booking_id,
    user_id,
    event_id,
    seat_number,
    booking_status,
    locked_until,
    created_at,
    confirmed_at,
    cancelled_at
FROM bookings
WHERE user_id = $1::uuid
ORDER BY created_at DESC
`

func (q *Queries) ListBookingsByUser(ctx context.Context, userID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.BookingID,
			&i.UserID,
			&i.EventID,
			&i.SeatNumber,
			&i.BookingStatus,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :execrows
UPDATE bookings
SET booking_status = $1::varchar,
    locked_until = $2::timestamptz,
    confirmed_at = CASE
        WHEN $1::varchar = 'CONFIRMED' THEN now()
        ELSE confirmed_at
    END
WHERE booking_id = $3::uuid
    AND booking_status = $4::varchar
`

type UpdateBookingStatusParams struct {
	NewStatus      string             `json:"new_status"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	BookingID      uuid.UUID          `json:"booking_id"`
	ExpectedStatus string             `json:"expected_status"`
}

// Guarded transition: only applies if the row is still in expected_status.
// This is the database-level optimistic-concurrency check (design doc
// Section 3.3.1, "Layer 2") — returns 0 affected rows (not an error) if
// another process already moved this booking out of the expected state.
func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBookingStatus,
		arg.NewStatus,
		arg.LockedUntil,
		arg.BookingID,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
