// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	BookingID     uuid.UUID          `json:"booking_id"`
	UserID        uuid.UUID          `json:"user_id"`
	EventID       uuid.UUID          `json:"event_id"`
	SeatNumber    string             `json:"seat_number"`
	BookingStatus string             `json:"booking_status"`
	LockedUntil   pgtype.Timestamptz `json:"locked_until"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt   pgtype.Timestamptz `json:"confirmed_at"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
}
