// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Step 3 in the sequence diagram (design doc Section 4.1): persist a PENDING
	// record before attempting the Redis lock, so even a failed lock attempt
	// leaves an auditable row.
	CreateBooking(ctx context.Context, arg CreateBookingParams) error
	// Input to the background TTL watcher (design doc Section 3.3.1, "automatic
	// reconciliation") — bookings stuck in LOCKED whose TTL has already passed.
	FindExpiredLocks(ctx context.Context, asOf pgtype.Timestamptz) ([]Booking, error)
	GetBookingByID(ctx context.Context, bookingID uuid.UUID) (Booking, error)
	ListBookingsByUser(ctx context.Context, userID uuid.UUID) ([]Booking, error)
	// Guarded transition: only applies if the row is still in expected_status.
	// This is the database-level optimistic-concurrency check (design doc
	// Section 3.3.1, "Layer 2") — returns 0 affected rows (not an error) if
	// another process already moved this booking out of the expected state.
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
